#define     EXPR
#define     TERM
#define     BINARY_OP
#define     UNARY_OP
#define     BRACES
#define     PLACE
#define     LITERAL
#define     PLUS
#define     MINUS
#define     MUL
#define     ASSIGN
#define     NEG
#define     NOT
#define     BOOL
#define     STR
#define     SYMB
#define     HEX
#define     BITS
#define     DEC
#define     IDENTIFIER
#define     BUILTIN_TYPE
#define     CUSTOM_TYPE
#define     ARRAY
#define     SOURCE_ITEM
#define     VAR
#define     SOURCE
#define     TYPE
#define     LIST
#define     INIT
#define     ARRAY_SIZE
#define     CALL
#define     INDEXER
#define     PRIMARY
#define     TYPEREF
#define     BLOCK
#define     FUNC_SIGNATURE
#define     FUNC_DEF
#define     ARGDEF_LIST
#define     ARGDEF
#define     NAME
#define     BREAK
#define     FUNC_CALL
#define     EXPR_LIST
#define     INDEXING
#define     WHILE
#define     DO_WHILE
#define     IF
#define     ELSE